# 5-1
studio = "Evil Angel"
print("Is studio = \"Evil Angel\"? I predict true.")
print(studio == "Evil Angel")
print("Are the first 4 characters = \"Evil\"? I predict true.")
print(studio[0:4] == "Evil")
print("Are the last 5 characters = \"Angel\"? I predict true.")
print(studio[-5:] == "Angel")
print("Are the last 3 characters = \"gel\"? I predict true.")
print(studio[-3:] == "gel")
print("Are characters 3 to 4 = \"il\"? I predict true.")
print(studio[2:4] == "il")

print("Is studio = \"Evil Angel\"? I predict true.")
print(studio != "Evil Angel")
print("Are the first 4 characters = \"Evil\"? I predict true.")
print(studio[0:4] != "Evil")
print("Are the last 5 characters = \"Angel\"? I predict true.")
print(studio[-5:] != "Angel")
print("Are the last 3 characters = \"gel\"? I predict true.")
print(studio[-3:] != "gel")
print("Are characters 3 to 4 = \"il\"? I predict true.")
print(studio[2:4] != "il")
